//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.MobileApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.MobileApp.Resources.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        internal static string Account_Details {
            get {
                return ResourceManager.GetString("Account Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        internal static string Add_Location {
            get {
                return ResourceManager.GetString("Add Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Quantity Type.
        /// </summary>
        internal static string Add_Quantity_Type {
            get {
                return ResourceManager.GetString("Add Quantity Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Status.
        /// </summary>
        internal static string Add_Status {
            get {
                return ResourceManager.GetString("Add Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        internal static string Address_1 {
            get {
                return ResourceManager.GetString("Address 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Address_2 {
            get {
                return ResourceManager.GetString("Address 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 3.
        /// </summary>
        internal static string Address_3 {
            get {
                return ResourceManager.GetString("Address 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty status was entered, nothing changed..
        /// </summary>
        internal static string An_empty_status_was_entered__nothing_changed_ {
            get {
                return ResourceManager.GetString("An empty status was entered, nothing changed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string Choose_Language {
            get {
                return ResourceManager.GetString("Choose Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme.
        /// </summary>
        internal static string Choose_Theme {
            get {
                return ResourceManager.GetString("Choose Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        internal static string Company_Details {
            get {
                return ResourceManager.GetString("Company Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string Company_Name {
            get {
                return ResourceManager.GetString("Company Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string Create_account {
            get {
                return ResourceManager.GetString("Create account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been verified..
        /// </summary>
        internal static string Email_has_been_verified_ {
            get {
                return ResourceManager.GetString("Email has been verified.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verification.
        /// </summary>
        internal static string Email_Verification {
            get {
                return ResourceManager.GetString("Email Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification failed..
        /// </summary>
        internal static string Email_verification_failed_ {
            get {
                return ResourceManager.GetString("Email verification failed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification code will be sent to {0}.
        ///
        ///Verified email is used to recover a lost account..
        /// </summary>
        internal static string EmailVerificationMessage {
            get {
                return ResourceManager.GetString("EmailVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Status.
        /// </summary>
        internal static string Empty_Status {
            get {
                return ResourceManager.GetString("Empty Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Credentials.
        /// </summary>
        internal static string Enter_Credentials {
            get {
                return ResourceManager.GetString("Enter Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the location description below..
        /// </summary>
        internal static string Enter_the_location_description_below_ {
            get {
                return ResourceManager.GetString("Enter the location description below.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the quantity type below..
        /// </summary>
        internal static string Enter_the_quantity_type_below_ {
            get {
                return ResourceManager.GetString("Enter the quantity type below.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the status description below..
        /// </summary>
        internal static string Enter_the_status_description_below_ {
            get {
                return ResourceManager.GetString("Enter the status description below.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code sent to {0}..
        /// </summary>
        internal static string EnterVerifCode {
            get {
                return ResourceManager.GetString("EnterVerifCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!  We encountered an error with your request.
        ///Would you like to share the error with us?.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username/password. Please try again..
        /// </summary>
        internal static string Incorrect_username_password__Please_try_again_ {
            get {
                return ResourceManager.GetString("Incorrect username/password. Please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Management.
        /// </summary>
        internal static string Inventory_Management {
            get {
                return ResourceManager.GetString("Inventory Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In.
        /// </summary>
        internal static string Logging_In {
            get {
                return ResourceManager.GetString("Logging In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found.
        /// </summary>
        internal static string No_items_found {
            get {
                return ResourceManager.GetString("No items found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a unique username..
        /// </summary>
        internal static string Please_enter_a_unique_username_ {
            get {
                return ResourceManager.GetString("Please enter a unique username.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Types.
        /// </summary>
        internal static string Qty_Types {
            get {
                return ResourceManager.GetString("Qty Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Types.
        /// </summary>
        internal static string Quantity_Types {
            get {
                return ResourceManager.GetString("Quantity Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering.
        /// </summary>
        internal static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Code.
        /// </summary>
        internal static string Sending_Code {
            get {
                return ResourceManager.GetString("Sending Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Barcode.
        /// </summary>
        internal static string Share_Barcode {
            get {
                return ResourceManager.GetString("Share Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        internal static string Statuses {
            get {
                return ResourceManager.GetString("Statuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating.
        /// </summary>
        internal static string Validating {
            get {
                return ResourceManager.GetString("Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
